version: '3.8'
services:
  fast-api:
    image: fast_api_app:v2
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - my-network
    depends_on:
      - neo4j

    # Добавьте другие параметры, такие как environment и volumes, если это необходимо
  neo4j:
    image: neo4j:4.4.3-community
    ports:
      - 7888:7474
      - 7999:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
    networks:
      - my-network
networks:
  my-network:
    driver: bridge