
GET http://127.0.0.1:8000/path/Матрица/Метод вычисления Определителя (понижением порядка)
###
GET http://127.0.0.1:8000/next/Матрица
###
GET http://127.0.0.1:8000/behind/Метод вычисления Определителя (сведением к треугольному виду)
###
GET http://127.0.0.1:8000
Content-Type: application/json

{
  "test": [
    {
      "theme": "Матрица",
      "complexity": 0,
      "answer": "True"
    },
    {
      "theme": "Матрица",
      "complexity": 1,
      "answer": "True"
    },
    {
      "theme": "Матрица",
      "complexity": 2,
      "answer": "True"
    }
  ],
  "studied": ["Комплексные числа"],
  "topic": "Метод вычисления Определителя (понижением порядка)"
}

